// GENERATED by npm run build:quran — do not edit by hand.
//
// The daily-ayah rotation, lifted verbatim out of assets/quran/quran.db so
// `dailyAyah()` can stay synchronous (its callers — the ayah card and the widget
// bridge — are both sync). `src/quran/verify.test.ts` re-reads the database and
// fails if a single character here has drifted from it.

export type CuratedAyah = {
  readonly surah: number;
  readonly ayah: number;
  /** Transliterated surah name, as the upstream index spells it. */
  readonly name: string;
  readonly arabic: string;
  readonly de: string;
  readonly en: string;
};

export const CURATED: readonly CuratedAyah[] = [
  {
    "surah": 2,
    "ayah": 152,
    "name": "Al-Baqara",
    "arabic": "فَٱذۡكُرُونِيٓ أَذۡكُرۡكُمۡ وَٱشۡكُرُواْ لِي وَلَا تَكۡفُرُونِ",
    "de": "Gedenkt Meiner, so gedenke Ich eurer. Seid Mir dankbar und seid nicht undankbar gegen Mich",
    "en": "Therefore remember Me; I will remember you. Be grateful to Me, and do not be ungrateful"
  },
  {
    "surah": 2,
    "ayah": 153,
    "name": "Al-Baqara",
    "arabic": "يَٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُواْ ٱسۡتَعِينُواْ بِٱلصَّبۡرِ وَٱلصَّلَوٰةِۚ إِنَّ ٱللَّهَ مَعَ ٱلصَّٰبِرِينَ",
    "de": "O die ihr glaubt, sucht Hilfe in der Standhaftigkeit und im Gebet! Allah ist mit den Standhaften",
    "en": "O you who believe, seek help in patience and prayer, for Allah is with those who are patient"
  },
  {
    "surah": 2,
    "ayah": 186,
    "name": "Al-Baqara",
    "arabic": "وَإِذَا سَأَلَكَ عِبَادِي عَنِّي فَإِنِّي قَرِيبٌۖ أُجِيبُ دَعۡوَةَ ٱلدَّاعِ إِذَا دَعَانِۖ فَلۡيَسۡتَجِيبُواْ لِي وَلۡيُؤۡمِنُواْ بِي لَعَلَّهُمۡ يَرۡشُدُونَ",
    "de": "Und wenn dich Meine Diener nach Mir fragen, so bin Ich nahe; Ich erhöre den Ruf des Bittenden, wenn er Mich anruft. So sollen sie nun auf Mich hören und an Mich glauben, auf daß sie besonnen handeln mögen",
    "en": "When My slaves ask you concerning Me, I am indeed near. I respond to the call of the supplicant when he calls upon Me; so they should respond to Me and believe in Me, so that they may be guided"
  },
  {
    "surah": 2,
    "ayah": 286,
    "name": "Al-Baqara",
    "arabic": "لَا يُكَلِّفُ ٱللَّهُ نَفۡسًا إِلَّا وُسۡعَهَاۚ لَهَا مَا كَسَبَتۡ وَعَلَيۡهَا مَا ٱكۡتَسَبَتۡۗ رَبَّنَا لَا تُؤَاخِذۡنَآ إِن نَّسِينَآ أَوۡ أَخۡطَأۡنَاۚ رَبَّنَا وَلَا تَحۡمِلۡ عَلَيۡنَآ إِصۡرࣰ ا كَمَا حَمَلۡتَهُۥ عَلَى ٱلَّذِينَ مِن قَبۡلِنَاۚ رَبَّنَا وَلَا تُحَمِّلۡنَا مَا لَا طَاقَةَ لَنَا بِهِۦۖ وَٱعۡفُ عَنَّا وَٱغۡفِرۡ لَنَا وَٱرۡحَمۡنَآۚ أَنتَ مَوۡلَىٰنَا فَٱنصُرۡنَا عَلَى ٱلۡقَوۡمِ ٱلۡكَٰفِرِينَ",
    "de": "Allah erlegt keiner Seele mehr auf, als sie zu leisten vermag. Ihr kommt (nur) zu, was sie verdient hat, und angelastet wird ihr (nur), was sie verdient hat. „Unser Herr, belange uns nicht, wenn wir (etwas) vergessen oder einen Fehler begehen. Unser Herr, lege uns keine Bürde auf, wie Du sie denjenigen vor uns auferlegt hast. Unser Herr, bürde uns nichts auf, wozu wir keine Kraft haben. Verzeihe uns, vergib uns und erbarme Dich unser! Du bist unser Schutzherr. So verhilf uns zum Sieg über das ungläubige Volk",
    "en": "Allah does not burden any soul greater than it can bear. For it is what it has earned, and against it is what it has incurred. “Our Lord, do not hold us accountable if we forget or fall into error. Our Lord, do not place on us such a burden as You have placed on those before us. Our Lord, do not burden us with that which we cannot bear. Pardon us, forgive us, and have mercy on us. You are our Protector, so give us victory over the disbelieving people.”"
  },
  {
    "surah": 3,
    "ayah": 139,
    "name": "Aal-i-Imraan",
    "arabic": "وَلَا تَهِنُواْ وَلَا تَحۡزَنُواْ وَأَنتُمُ ٱلۡأَعۡلَوۡنَ إِن كُنتُم مُّؤۡمِنِينَ",
    "de": "Und werdet nicht schwach noch seid traurig, wo ihr doch die Oberhand haben werdet, wenn ihr gläubig seid",
    "en": "Do not lose heart nor grieve, for you have the upper hand, if you are [truly] believers"
  },
  {
    "surah": 3,
    "ayah": 173,
    "name": "Aal-i-Imraan",
    "arabic": "ٱلَّذِينَ قَالَ لَهُمُ ٱلنَّاسُ إِنَّ ٱلنَّاسَ قَدۡ جَمَعُواْ لَكُمۡ فَٱخۡشَوۡهُمۡ فَزَادَهُمۡ إِيمَٰنࣰ ا وَقَالُواْ حَسۡبُنَا ٱللَّهُ وَنِعۡمَ ٱلۡوَكِيلُ",
    "de": "Diejenigen, zu denen die Menschen sagten: „Die Menschen haben (sich) bereits gegen euch versammelt; darum fürchtet sie! - Doch da mehrte das (nur) ihren Glauben, und sie sagten: „Unsere Genüge ist Allah, und wie trefflich ist der Sachwalter",
    "en": "those to whom people said, “Indeed, the people have gathered against you, so fear them.” But it only increased them in faith, and they said, “Allah is Sufficient for us, and He is the best Protector.”"
  },
  {
    "surah": 3,
    "ayah": 200,
    "name": "Aal-i-Imraan",
    "arabic": "يَٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُواْ ٱصۡبِرُواْ وَصَابِرُواْ وَرَابِطُواْ وَٱتَّقُواْ ٱللَّهَ لَعَلَّكُمۡ تُفۡلِحُونَ",
    "de": "O die ihr glaubt, geduldet euch, haltet standhaft aus, seid kampfbereit und fürchtet Allah, auf daß es euch wohl ergehen möge",
    "en": "O you who believe, be patient and endure, stand on guard and fear Allah, so that you may be successful"
  },
  {
    "surah": 8,
    "ayah": 46,
    "name": "Al-Anfaal",
    "arabic": "وَأَطِيعُواْ ٱللَّهَ وَرَسُولَهُۥ وَلَا تَنَٰزَعُواْ فَتَفۡشَلُواْ وَتَذۡهَبَ رِيحُكُمۡۖ وَٱصۡبِرُوٓاْۚ إِنَّ ٱللَّهَ مَعَ ٱلصَّٰبِرِينَ",
    "de": "Und gehorcht Allah und Seinem Gesandten, und streitet nicht miteinander, sonst würdet ihr den Mut verlieren, und eure Kraft würde vergehen! Und seid standhaft! Gewiß, Allah ist mit den Standhaften",
    "en": "Obey Allah and His Messenger, and do not dispute with one another, or else you will lose courage and your strength will weaken. And be steadfast, for Allah is with those who are steadfast"
  },
  {
    "surah": 9,
    "ayah": 51,
    "name": "At-Tawba",
    "arabic": "قُل لَّن يُصِيبَنَآ إِلَّا مَا كَتَبَ ٱللَّهُ لَنَا هُوَ مَوۡلَىٰنَاۚ وَعَلَى ٱللَّهِ فَلۡيَتَوَكَّلِ ٱلۡمُؤۡمِنُونَ",
    "de": "Sag: Uns wird nur das treffen, was Allah für uns bestimmt hat. Er ist unser Schutzherr. Auf Allah sollen sich die Gläubigen verlassen",
    "en": "Say, “Nothing will ever befall us except that which Allah has decreed for us; He is our Protector.” And in Allah alone let the believers put their trust"
  },
  {
    "surah": 10,
    "ayah": 62,
    "name": "Yunus",
    "arabic": "أَلَآ إِنَّ أَوۡلِيَآءَ ٱللَّهِ لَا خَوۡفٌ عَلَيۡهِمۡ وَلَا هُمۡ يَحۡزَنُونَ",
    "de": "Sicherlich, über Allahs Gefolgsleute soll keine Furcht kommen, noch sollen sie traurig sein",
    "en": "Indeed, the allies of Allah will have no fear, nor will they grieve"
  },
  {
    "surah": 12,
    "ayah": 87,
    "name": "Yusuf",
    "arabic": "يَٰبَنِيَّ ٱذۡهَبُواْ فَتَحَسَّسُواْ مِن يُوسُفَ وَأَخِيهِ وَلَا تَاْيۡـَٔسُواْ مِن رَّوۡحِ ٱللَّهِۖ إِنَّهُۥ لَا يَاْيۡـَٔسُ مِن رَّوۡحِ ٱللَّهِ إِلَّا ٱلۡقَوۡمُ ٱلۡكَٰفِرُونَ",
    "de": "O meine Kinder, geht und erkundigt euch über Yusuf und seinen Bruder. Und gebt nicht die Hoffnung auf das Erbarmen Allahs auf. Es gibt die Hoffnung auf das Erbarmen Allahs nur das ungläubige Volk auf",
    "en": "O my sons, go and find out about Joseph and his brother, and do not despair of Allah’s mercy. Indeed, no one despairs of Allah’s mercy except the disbelieving people.”"
  },
  {
    "surah": 13,
    "ayah": 28,
    "name": "Ar-Ra'd",
    "arabic": "ٱلَّذِينَ ءَامَنُواْ وَتَطۡمَئِنُّ قُلُوبُهُم بِذِكۡرِ ٱللَّهِۗ أَلَا بِذِكۡرِ ٱللَّهِ تَطۡمَئِنُّ ٱلۡقُلُوبُ",
    "de": "(Es sind) diejenigen, die glauben und deren Herzen im Gedenken Allahs Ruhe finden. Sicherlich, im Gedenken Allahs finden die Herzen Ruhe",
    "en": "those who believe and whose hearts find tranquility in the remembrance of Allah, for indeed in the remembrance of Allah do hearts find tranquility"
  },
  {
    "surah": 14,
    "ayah": 7,
    "name": "Ibrahim",
    "arabic": "وَإِذۡ تَأَذَّنَ رَبُّكُمۡ لَئِن شَكَرۡتُمۡ لَأَزِيدَنَّكُمۡۖ وَلَئِن كَفَرۡتُمۡ إِنَّ عَذَابِي لَشَدِيدࣱ‏",
    "de": "Und als euer Herr ankündigte: ,Wenn ihr dankbar seid, werde Ich euch ganz gewiß noch mehr (Gunst) erweisen. Wenn ihr jedoch undankbar seid, dann ist meine Strafe fürwahr streng",
    "en": "And [remember] when your Lord declared, ‘If you are grateful, I will surely give you more; but if you are ungrateful, My punishment is severe indeed.’”"
  },
  {
    "surah": 16,
    "ayah": 97,
    "name": "An-Nahl",
    "arabic": "مَنۡ عَمِلَ صَٰلِحࣰ ا مِّن ذَكَرٍ أَوۡ أُنثَىٰ وَهُوَ مُؤۡمِنࣱ فَلَنُحۡيِيَنَّهُۥ حَيَوٰةࣰ طَيِّبَةࣰۖ وَلَنَجۡزِيَنَّهُمۡ أَجۡرَهُم بِأَحۡسَنِ مَا كَانُواْ يَعۡمَلُونَ",
    "de": "Wer rechtschaffen handelt, sei es Mann oder Frau, und dabei gläubig ist, den werden Wir ganz gewiß ein gutes Leben leben lassen. Und Wir werden ihnen ganz gewiß mit ihrem Lohn das Beste von dem vergelten, was sie taten",
    "en": "Whoever does righteous deeds, male or female, while being a believer, We will surely grant him a good life, and We will surely reward them according to the best of their deeds"
  },
  {
    "surah": 16,
    "ayah": 128,
    "name": "An-Nahl",
    "arabic": "إِنَّ ٱللَّهَ مَعَ ٱلَّذِينَ ٱتَّقَواْ وَّٱلَّذِينَ هُم مُّحۡسِنُونَ",
    "de": "Gewiß, Allah ist mit denjenigen, die gottesfürchtig sind und Gutes tun",
    "en": "Indeed, Allah is with those who fear Him and those who do good"
  },
  {
    "surah": 20,
    "ayah": 46,
    "name": "Taa-Haa",
    "arabic": "قَالَ لَا تَخَافَآۖ إِنَّنِي مَعَكُمَآ أَسۡمَعُ وَأَرَىٰ",
    "de": "Er sagte: „Fürchtet euch nicht. Ich bin gewiß mit euch, Ich höre und Ich sehe (, was geschieht)",
    "en": "He said, “Do not be afraid; I am with you both, hearing and seeing"
  },
  {
    "surah": 25,
    "ayah": 74,
    "name": "Al-Furqaan",
    "arabic": "وَٱلَّذِينَ يَقُولُونَ رَبَّنَا هَبۡ لَنَا مِنۡ أَزۡوَٰجِنَا وَذُرِّيَّٰتِنَا قُرَّةَ أَعۡيُنࣲ وَٱجۡعَلۡنَا لِلۡمُتَّقِينَ إِمَامًا",
    "de": "Und diejenigen, die sagen: „Unser Herr, schenke uns an unseren Gattinnen und unseren Nachkommenschaften Grund zur Freude, und mache uns für die Rechtschaffenen zu einem Vorbild",
    "en": "and those who say, “Our Lord, let our spouses and children be a source of joy for us, and make us good examples for the righteous.”"
  },
  {
    "surah": 29,
    "ayah": 69,
    "name": "Al-Ankaboot",
    "arabic": "وَٱلَّذِينَ جَٰهَدُواْ فِينَا لَنَهۡدِيَنَّهُمۡ سُبُلَنَاۚ وَإِنَّ ٱللَّهَ لَمَعَ ٱلۡمُحۡسِنِينَ",
    "de": "Diejenigen aber, die sich um Unsertwillen abmühen, werden Wir ganz gewiß Unsere Wege leiten. Und Allah ist wahrlich mit den Gutes Tuenden",
    "en": "As for those who strive in Our cause, We will surely guide them to Our ways, for Allah is certainly with those who do good"
  },
  {
    "surah": 33,
    "ayah": 3,
    "name": "Al-Ahzaab",
    "arabic": "وَتَوَكَّلۡ عَلَى ٱللَّهِۚ وَكَفَىٰ بِٱللَّهِ وَكِيلࣰ ا",
    "de": "Und verlasse dich auf Allah. Allah genügt als Sachwalter",
    "en": "Put your trust in Allah; sufficient is Allah as a Disposer of Affairs"
  },
  {
    "surah": 39,
    "ayah": 53,
    "name": "Az-Zumar",
    "arabic": "۞قُلۡ يَٰعِبَادِيَ ٱلَّذِينَ أَسۡرَفُواْ عَلَىٰٓ أَنفُسِهِمۡ لَا تَقۡنَطُواْ مِن رَّحۡمَةِ ٱللَّهِۚ إِنَّ ٱللَّهَ يَغۡفِرُ ٱلذُّنُوبَ جَمِيعًاۚ إِنَّهُۥ هُوَ ٱلۡغَفُورُ ٱلرَّحِيمُ",
    "de": "Sag: O Meine Diener, die ihr gegen euch selbst maßlos gewesen seid, verliert nicht die Hoffnung auf Allahs Barmherzigkeit. Gewiß, Allah vergibt die Sünden alle. Er ist ja der Allvergebende und Barmherzige",
    "en": "Say [Allah says], “O My slaves who have transgressed against themselves, do not despair of Allah’s mercy, for indeed Allah forgives all sins. He is indeed the All-Forgiving, the Most Merciful"
  },
  {
    "surah": 40,
    "ayah": 60,
    "name": "Ghafir",
    "arabic": "وَقَالَ رَبُّكُمُ ٱدۡعُونِيٓ أَسۡتَجِبۡ لَكُمۡۚ إِنَّ ٱلَّذِينَ يَسۡتَكۡبِرُونَ عَنۡ عِبَادَتِي سَيَدۡخُلُونَ جَهَنَّمَ دَاخِرِينَ",
    "de": "Euer Herr sagt: Ruft Mich an, so erhöre Ich euch. Gewiß, diejenigen, die sich aus Hochmut weigern, Mir zu dienen, werden in die Hölle gedemütigt eingehen",
    "en": "Your Lord says, “Call upon Me; I will respond to you. Those who are too proud to worship Me will enter Hell, utterly debased.”"
  },
  {
    "surah": 47,
    "ayah": 7,
    "name": "Muhammad",
    "arabic": "يَٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوٓاْ إِن تَنصُرُواْ ٱللَّهَ يَنصُرۡكُمۡ وَيُثَبِّتۡ أَقۡدَامَكُمۡ",
    "de": "O die ihr glaubt, wenn ihr Allah(s Sache) helft, hilft Er euch und festigt eure Füße",
    "en": "O you who believe, if you stand up for Allah, He will help you and make your steps firm"
  },
  {
    "surah": 55,
    "ayah": 60,
    "name": "Ar-Rahmaan",
    "arabic": "هَلۡ جَزَآءُ ٱلۡإِحۡسَٰنِ إِلَّا ٱلۡإِحۡسَٰنُ",
    "de": "Ist der Lohn des Guten nicht ebenfalls das Gute",
    "en": "Is the reward for goodness anything but goodness"
  },
  {
    "surah": 64,
    "ayah": 11,
    "name": "At-Taghaabun",
    "arabic": "مَآ أَصَابَ مِن مُّصِيبَةٍ إِلَّا بِإِذۡنِ ٱللَّهِۗ وَمَن يُؤۡمِنۢ بِٱللَّهِ يَهۡدِ قَلۡبَهُۥۚ وَٱللَّهُ بِكُلِّ شَيۡءٍ عَلِيمࣱ‏",
    "de": "Kein Unglück trifft (jemanden), außer mit Allahs Erlaubnis. Und wer an Allah glaubt, dessen Herz leitet Er recht. Und Allah weiß über alles Bescheid",
    "en": "No calamity befalls except with Allah’s permission. Whoever believes in Allah, He will guide his heart. And Allah is All-Knowing of everything"
  },
  {
    "surah": 65,
    "ayah": 3,
    "name": "At-Talaaq",
    "arabic": "وَيَرۡزُقۡهُ مِنۡ حَيۡثُ لَا يَحۡتَسِبُۚ وَمَن يَتَوَكَّلۡ عَلَى ٱللَّهِ فَهُوَ حَسۡبُهُۥٓۚ إِنَّ ٱللَّهَ بَٰلِغُ أَمۡرِهِۦۚ قَدۡ جَعَلَ ٱللَّهُ لِكُلِّ شَيۡءࣲ قَدۡرࣰ ا",
    "de": "und gewährt ihm Versorgung, von wo (aus) er damit nicht rechnet. Und wer sich auf Allah verläßt, dem ist Er seine Genüge. Allah wird gewiß (die Durchführung) seine(r) Angelegenheit erreichen. Allah legt ja für alles ein Maß fest",
    "en": "and He will provide for him from where he does not expect. Whoever puts his trust in Allah, He is sufficient for him. Indeed, Allah will surely accomplish His purpose, for Allah has set a destiny for everything"
  },
  {
    "surah": 92,
    "ayah": 7,
    "name": "Al-Lail",
    "arabic": "فَسَنُيَسِّرُهُۥ لِلۡيُسۡرَىٰ",
    "de": "so werden Wir ihm den Weg zum Leichteren leicht machen",
    "en": "We will make easy for him the way of salvation"
  },
  {
    "surah": 93,
    "ayah": 5,
    "name": "Ad-Dhuhaa",
    "arabic": "وَلَسَوۡفَ يُعۡطِيكَ رَبُّكَ فَتَرۡضَىٰٓ",
    "de": "Und dein Herr wird dir wahrlich geben, und dann wirst du zufrieden sein",
    "en": "and your Lord will certainly give you so much that you will be well pleased"
  },
  {
    "surah": 93,
    "ayah": 7,
    "name": "Ad-Dhuhaa",
    "arabic": "وَوَجَدَكَ ضَآلࣰّ ا فَهَدَىٰ",
    "de": "und dich irregehend gefunden und dann rechtgeleitet",
    "en": "Did He not find you unguided then guide you"
  },
  {
    "surah": 94,
    "ayah": 5,
    "name": "Ash-Sharh",
    "arabic": "فَإِنَّ مَعَ ٱلۡعُسۡرِ يُسۡرًا",
    "de": "Also gewiß, mit der Erschwernis ist Erleichterung",
    "en": "For indeed, with hardship comes ease"
  },
  {
    "surah": 94,
    "ayah": 6,
    "name": "Ash-Sharh",
    "arabic": "إِنَّ مَعَ ٱلۡعُسۡرِ يُسۡرࣰ ا",
    "de": "gewiß, mit der Erschwernis ist Erleichterung",
    "en": "indeed, with hardship comes ease"
  }
];
