// GENERATED by npm run gen:theme from src/theme/tokens.ts — do not edit by hand.
//
// Read by the widget extension, the Shield Configuration extension and the
// Shield Action extension. Those run in their own processes and cannot reach
// the JS bundle, so the values have to be compiled in — which is exactly why
// the parity test exists.

import SwiftUI

enum Theme {
    /// light #EDEEE9 · dark #101413
    static let ground = Color(UIColor { $0.userInterfaceStyle == .dark
        ? UIColor(hex: 0x101413) : UIColor(hex: 0xEDEEE9) })
    /// light #FFFFFF · dark #181D1C
    static let surface = Color(UIColor { $0.userInterfaceStyle == .dark
        ? UIColor(hex: 0x181D1C) : UIColor(hex: 0xFFFFFF) })
    /// light #171C1A · dark #E8EBE8
    static let ink = Color(UIColor { $0.userInterfaceStyle == .dark
        ? UIColor(hex: 0xE8EBE8) : UIColor(hex: 0x171C1A) })
    /// light #5E6866 · dark #929C99
    static let inkMuted = Color(UIColor { $0.userInterfaceStyle == .dark
        ? UIColor(hex: 0x929C99) : UIColor(hex: 0x5E6866) })
    /// light #CFD3CE · dark #2A302E
    static let hairline = Color(UIColor { $0.userInterfaceStyle == .dark
        ? UIColor(hex: 0x2A302E) : UIColor(hex: 0xCFD3CE) })
    /// light #15564A · dark #4E9E8A
    static let accent = Color(UIColor { $0.userInterfaceStyle == .dark
        ? UIColor(hex: 0x4E9E8A) : UIColor(hex: 0x15564A) })
    /// light #F2F1EA · dark #0B100F
    static let accentInk = Color(UIColor { $0.userInterfaceStyle == .dark
        ? UIColor(hex: 0x0B100F) : UIColor(hex: 0xF2F1EA) })
    /// light #A6412B · dark #E07B5F
    static let now = Color(UIColor { $0.userInterfaceStyle == .dark
        ? UIColor(hex: 0xE07B5F) : UIColor(hex: 0xA6412B) })
}

extension UIColor {
    /// 0xRRGGBB -> UIColor. sRGB, full alpha.
    convenience init(hex: UInt32) {
        self.init(
            red: CGFloat((hex >> 16) & 0xFF) / 255,
            green: CGFloat((hex >> 8) & 0xFF) / 255,
            blue: CGFloat(hex & 0xFF) / 255,
            alpha: 1
        )
    }
}
