/**
 * Generates the native colour files from src/theme/tokens.ts.
 *
 *   npm run gen:theme
 *
 * Run with plain `node` — Node 24 strips TypeScript types natively, so this
 * needs no ts-node, no tsx, no build step.
 *
 * Why generate instead of hand-maintaining three files: a person editing
 * Theme.swift has no reason to think about an Android resource file, and a
 * person editing tokens.ts has no reason to think about either. Nothing notices
 * the drift except a test. `src/theme/parity.test.ts` re-runs this generator in
 * memory and fails if what is on disk differs, so the failure message is always
 * "run npm run gen:theme" rather than a hunt.
 */
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { light, dark, type ColorToken, type Palette } from '../src/theme/tokens.ts';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const BANNER = 'GENERATED by npm run gen:theme from src/theme/tokens.ts — do not edit by hand.';

/** ground -> ground_color? No: ground -> ground. accentInk -> accent_ink. */
const snake = (k: string) => k.replace(/[A-Z]/g, (c) => '_' + c.toLowerCase());

const order = Object.keys(light) as ColorToken[];

export function swiftSource(l: Palette, d: Palette): string {
  const props = order
    .map((k) => {
      const hex = (p: Palette) => p[k].replace('#', '0x');
      return (
        `    /// light ${l[k]} · dark ${d[k]}\n` +
        `    static let ${k} = Color(UIColor { $0.userInterfaceStyle == .dark\n` +
        `        ? UIColor(hex: ${hex(d)}) : UIColor(hex: ${hex(l)}) })`
      );
    })
    .join('\n');

  return `// ${BANNER}
//
// Read by the widget extension, the Shield Configuration extension and the
// Shield Action extension. Those run in their own processes and cannot reach
// the JS bundle, so the values have to be compiled in — which is exactly why
// the parity test exists.

import SwiftUI

enum Theme {
${props}
}

extension UIColor {
    /// 0xRRGGBB -> UIColor. sRGB, full alpha.
    convenience init(hex: UInt32) {
        self.init(
            red: CGFloat((hex >> 16) & 0xFF) / 255,
            green: CGFloat((hex >> 8) & 0xFF) / 255,
            blue: CGFloat(hex & 0xFF) / 255,
            alpha: 1
        )
    }
}
`;
}

export function colorsXml(p: Palette, appearance: 'light' | 'dark'): string {
  const rows = order
    .map((k) => `    <color name="${snake(k)}">${p[k].toUpperCase()}</color>`)
    .join('\n');
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- ${BANNER} -->
<!-- ${appearance} appearance -->
<resources>
${rows}
</resources>
`;
}

/** path relative to repo root -> file contents. The parity test compares this map to disk. */
export function generated(): Record<string, string> {
  return {
    // Lives INSIDE the widget target: @bacons/apple-targets links every file in
    // targets/<name>/ into that target, so a shared/ folder would never compile in.
    'targets/widget/Theme.swift': swiftSource(light, dark),
    'modules/rakat-blocking/android/src/main/res/values/colors.xml': colorsXml(light, 'light'),
    'modules/rakat-blocking/android/src/main/res/values-night/colors.xml': colorsXml(dark, 'dark'),
  };
}

export function readFromDisk(rel: string): string | null {
  try {
    return readFileSync(join(root, rel), 'utf8');
  } catch {
    return null;
  }
}

// Only write when invoked directly, so the parity test can import the pure bits.
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  for (const [rel, body] of Object.entries(generated())) {
    const abs = join(root, rel);
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, body);
    console.log('wrote', rel);
  }
}
